/*=========================================================================

        Program:   Visualization Toolkit
        Module:    vtkFrameToTimeStampConverter.h

	David Gobbi 
	Imaging Research Laboratories
        John P. Robarts Research Institute
        Box 5015, 100 Perth Drive
	London, Ontario

        dgobbi@irus.rri.on.ca
	(519)663-5777x34213

==========================================================================

Copyright (c) 2000 Atamai, Inc.

Use, modification and redistribution of the software, in source or
binary forms, are permitted provided that the following terms and
conditions are met:

1) Redistribution of the source code, in verbatim or modified
   form, must retain the above copyright notice, this license,
   the following disclaimer, and any notices that refer to this
   license and/or the following disclaimer.  

2) Redistribution in binary form must include the above copyright
   notice, a copy of this license and the following disclaimer
   in the documentation or with other materials provided with the
   distribution.

3) Modified copies of the source code must be clearly marked as such,
   and must not be misrepresented as verbatim copies of the source code.

THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE SOFTWARE "AS IS"
WITHOUT EXPRESSED OR IMPLIED WARRANTY INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.  IN NO EVENT SHALL ANY COPYRIGHT HOLDER OR OTHER PARTY WHO MAY
MODIFY AND/OR REDISTRIBUTE THE SOFTWARE UNDER THE TERMS OF THIS LICENSE
vBE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, LOSS OF DATA OR DATA BECOMING INACCURATE
OR LOSS OF PROFIT OR BUSINESS INTERRUPTION) ARISING IN ANY WAY OUT OF
THE USE OR INABILITY TO USE THE SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGES.

=========================================================================*/
// .NAME vtkFrameToTimeStampConverter - accurate timing of events
// .SECTION Description
// The vtkFrameToTimeStampConverter is used to generate accurate
// timestamps for data records that are known to be generated at
// a regular frequency, such as video frames generated at 30Hz.
// If timestamps are generated by simply reading the system clock,
// then errors of +/- 10ms are common because the 'quantum' for
// process scheduling is usually around 20ms.  Through the use of
// this class and the assumption that the measurement frames are
// evenly spaced, the error is reduced to around +/- 2ms.
// .SECTION see also
// vtkPOLARISTracker vtkFlockTracker

#ifndef __vtkFrameToTimeStampConverter_h
#define __vtkFrameToTimeStampConverter_h

#include "vtkObject.h"

class VTK_EXPORT vtkFrameToTimeStampConverter : public vtkObject
{
public:
  static vtkFrameToTimeStampConverter *New();
  vtkTypeMacro(vtkFrameToTimeStampConverter,vtkObject);
  void PrintSelf(ostream& os, vtkIndent indent);

  // Description:
  // Set the nominal frequency of the measurement frames.  The default
  // nominal frequency is 100Hz.
  void SetNominalFrequency(double f) { this->NominalFrequency = f; };
  double GetNominalFrequency() { return this->NominalFrequency; };

  // Description:
  // Initialize, this should be done after the nominal frequency is
  // set but before the object is used.
  void Initialize();

  // Description:
  // Give the frame number of the data record that was most recently
  // obtained from the measurement system, i.e. give the frame number
  // that corresponds most closely with 'now'.  The instantanous
  // frequency is estimated within this method, and used to update
  // the virtual clock.  If the given frame is less than or equal
  // to the current LastFrame, it will be quietly ignored.
  // If the measuring device does not provide 'frames' then it
  // is reasonable to use SetLastFrame(GetLastFrame() + 1).
  void SetLastFrame(unsigned long frame);
  unsigned long GetLastFrame() { return this->LastFrameCount; };
  
  // Description:
  // Generate a timestamp for a particular frame.  The frame must
  // not be greater than the LastFrame.
  double GetTimeStampForFrame(unsigned long frame);

  // Description:
  // Get the measured frame frequency (which hopefully should not
  // be much different from the nominal frequency).
  double GetInstantaneousFrequency();

protected:
  vtkFrameToTimeStampConverter();
  ~vtkFrameToTimeStampConverter();

  double NominalFrequency;
  double LastTimeStamp;
  unsigned long LastFrameCount;
  unsigned long LastLastFrameCount;
  double EstimatedFramePeriod;
  double NextFramePeriod;

private:
  vtkFrameToTimeStampConverter(const vtkFrameToTimeStampConverter&);
  void operator=(const vtkFrameToTimeStampConverter&);  
};

#endif

