name: Build-Windows

on: [push, pull_request]
env:
  BUILD_TYPE: Release
  QT_VERSION: 5.15.2
  ARTIFACT: ibis-install-windows
  RELEASE_TAG: latest_dev
permissions:
  contents: write
jobs:
  build:
    runs-on: [self-hosted, windows, x64 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure CMake
        run: cmake IbisSuperBuild 
            -G "Visual Studio 17 2022" \
            -A x64 \
            -B ${{github.workspace}}/b \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_CONFIGURATION_TYPES=${{env.BUILD_TYPE}} \
            -DQt5_DIR=C:/Qt/5.15.2/msvc2019_64/lib/cmake/Qt5 \
            -DIBIS_BUILD_ELASTIX=TRUE \
            -DIBIS_BUILD_OPENCV=TRUE \
            -DIBIS_BUILD_ALL_PLUGINS:BOOL=TRUE

      - name: Build
        run: cmake --build ${{github.workspace}}/b --config ${{env.BUILD_TYPE}} -j2

      - name: Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{github.workspace}}/b/Ibis/Ibis/${{env.BUILD_TYPE}}
          
      # When updating master, create realease
      - name: Zip build and tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        working-directory: ${{github.workspace}}
        run:  |
              7z a ${{ env.ARTIFACT }}.zip ${{github.workspace}}/b/Ibis/Ibis/${{env.BUILD_TYPE}} -r
              git tag -f ${{ env.RELEASE_TAG }}
              git push -f origin ${{ env.RELEASE_TAG }}
      - name: Update GitHub release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          name: Latest development build
          artifacts: ${{ env.ARTIFACT }}.zip
          allowUpdates: true
          artifactErrorsFailBuild: true
          commit: master
          # makeLatest: true
          prerelease: true
          replacesArtifacts: true
          updateOnlyUnreleased: true
